#!/bin/bash
case "$1" in
  record)
    echo "Recording terminal session."
    echo "  \`exit\` to finish."
    shift
    "${BASH_SOURCE%/*}/record.sh" $*;;
  play)
    shift
    "${BASH_SOURCE%/*}/play.sh" $*;;
  publish)
    shift
    "${BASH_SOURCE%/*}/publish.sh" $*;;
  download)
    shift
    "${BASH_SOURCE%/*}/download.sh" $*;;
esac

